
import { GrooveObject, NoteEvent, ChannelKey } from '../types';
import { QAResult } from './qaService';
import { ELITE_16_CHANNELS } from './maestroService';

export const reportService = {
    generateReport: (groove: GrooveObject, qaResult: QAResult, params: { runId: string, generationType: string }): string => {
        const timestamp = new Date().toLocaleString();
        
        let report = `
============================================================
MIDI AI - MASTER FORENSIC REPORT (V107)
============================================================
Project Identity:   ${groove.name || "Neural Synthesis"}
Run Reference:      ${params.runId}
Synthesis Node:     Maestro Engine V107.4
Timestamp:          ${timestamp}
============================================================

[1] CORE MUSICAL PARAMETERS
------------------------------------------------------------
Status:             VERIFIED
Target Genre:       ${groove.genre || "Full-On Psytrance"}
Tempo:              ${groove.bpm} BPM
Musical Key:        ${groove.key}
Scale Profile:      ${groove.scale} (Phrygian Standard)
Project Length:     ${groove.totalBars} Bars (~${((groove.totalBars || 0) * 4 / (groove.bpm || 1)).toFixed(2)} Minutes)
------------------------------------------------------------

[2] CHANNEL MANIFEST & FORENSIC DENSITY
------------------------------------------------------------
The following 15 Elite channels were synthesized and validated:

`;

        ELITE_16_CHANNELS.forEach(ch => {
            const notes = (groove as any)[ch] as NoteEvent[] || [];
            const count = notes.length;
            const activeBars = qaResult.forensicData.channelActivity[ch] || 0;
            const coverage = Math.round((activeBars / (groove.totalBars || 1)) * 100);
            
            const status = count > 0 ? "SYNCHRONIZED" : "EMPTY/IDLE";
            const role = ch.includes('kick') ? 'Rhythmic Anchor' : 
                         ch.includes('sub') ? 'Foundation Sub' :
                         ch.includes('lead') ? 'Melodic Hero' :
                         ch.includes('arp') ? 'Atmospheric Motion' :
                         ch.includes('perc') ? 'Tribal Texture' : 'Drums/Perc';

            report += `- ${ch.padEnd(16)} | Status: ${status.padEnd(14)} | Events: ${count.toString().padEnd(4)} | Role: ${role}\n`;
            if (count > 0) {
                report += `   Timeline Coverage: ${coverage}% | Density: ${(count / (groove.totalBars || 1)).toFixed(1)} notes/bar\n`;
            }
        });

        report += `
------------------------------------------------------------

[3] NEURAL ARRANGEMENT BLUEPRINT
------------------------------------------------------------
Maestro Section Map:

`;

        if (groove.structureMap) {
            groove.structureMap.forEach((s, i) => {
                report += `${(i + 1).toString().padStart(2)}. [${s.type}] Bars ${s.startBar.toString().padStart(3)} - ${(s.startBar + s.durationBars).toString().padStart(3)} | Energy: ${s.energy}\n`;
                report += `    Active Channels: ${s.activeInstruments.length} synthesized layers\n`;
            });
        }

        report += `
------------------------------------------------------------

[4] QUALITY ASSURANCE (QA) SCORECARD
------------------------------------------------------------
Final Integrity Score: ${qaResult.score}/100

Detailed Diagnostics:
- Structural Sync:     ${qaResult.subScores.structural}/20
- Genre Adherence:     ${qaResult.subScores.genre}/25
- Low-End Authority:   ${qaResult.subScores.lowEnd}/20 (Kick/Bass relationship)
- Harmonic Validity:   ${qaResult.subScores.harmonic}/15
- Density Logic:       ${qaResult.subScores.density}/10
- AI Intelligence:     ${qaResult.subScores.intelligence}/10

Forensic Warnings:
${qaResult.forensicData.warnings.length > 0 
    ? qaResult.forensicData.warnings.map(w => `⚠️ ${w}`).join('\n') 
    : "✅ No critical anomalies detected. Project is broadcast ready."}

Harmonic Conflicts:
${qaResult.forensicData.harmonicConflicts.length > 0
    ? qaResult.forensicData.harmonicConflicts.map(c => `! ${c}`).join('\n')
    : "✅ 100% Harmonic Alignment detected."}

------------------------------------------------------------

[5] ENGINE SOURCE LOGS
------------------------------------------------------------
- Grid Lock: Enabled (1/16 Quantization)
- Bass Sanitization: Applied (No overlaps)
- Lead Humanization: 15% Velocity Variance
- Conductor Policy: Active (Statement vs Rest logic)

============================================================
END OF FORENSIC DUMP - GENERATED BY MIDI AI
============================================================
`;
        return report;
    }
};
