
import React, { useState, useCallback } from 'react';
import { useDropzone } from 'react-dropzone';
import { learningBrainService } from '../services/learningBrainService';
import { referenceAnalysisService } from '../services/referenceAnalysisService';
import { referenceStorageService } from '../services/referenceStorageService';
// Added AlertTriangle to imports
import { BrainCircuit, Upload, FileCode, CheckCircle, ArrowLeft, Loader2, Database, FileText, ShieldCheck, AlertTriangle } from 'lucide-react';
import { ChannelKey } from '../types';

interface NeuralTrainerProps {
    onClose: () => void;
}

interface QueuedFile {
    file: File;
    status: 'PENDING' | 'ANALYZING' | 'LEARNED' | 'FAILED';
    stats?: any;
    detectedRole?: string;
}

const detectRole = (filename: string): ChannelKey | string => {
  const lower = filename.toLowerCase();
  if (lower.includes('kick')) return 'ch1_kick';
  if (lower.includes('sub')) return 'ch2_sub'; 
  if (lower.includes('bass')) return 'ch3_midBass';
  if (lower.includes('lead') || lower.includes('main')) return 'ch4_leadA';
  if (lower.includes('acid') || lower.includes('303')) return 'ch14_acid';
  if (lower.includes('arp')) return 'ch6_arpA';
  if (lower.includes('pad') || lower.includes('atmos')) return 'ch15_pad';
  return 'UNKNOWN';
};

// Helper to generate and download TXT report
const downloadLearningReport = (fileName: string, dna: any, role: string) => {
    const timestamp = new Date().toLocaleString('he-IL');
    const report = `
============================================================
   MIDI AI - NEURAL LEARNING AUDIT REPORT
============================================================
DATE:           ${timestamp}
SOURCE FILE:    ${fileName}
DETECTED ROLE:  ${role.toUpperCase()}
STATUS:         COMMITTED TO PERMANENT BRAIN (V38)
============================================================

[1] EXTRACTED DNA CHARACTERISTICS
------------------------------------------------------------
- BPM ESTIMATE:     ${dna.bpmEstimate} BPM
- NOTE DENSITY:     ${(dna.noteDensityAvg * 16).toFixed(2)} notes per bar
- PITCH RANGE:      ${dna.pitchRange.min} to ${dna.pitchRange.max} (MIDI)
- VELOCITY AVG:     ${(dna.velocityAvg * 100).toFixed(0)}% Intensity
- SYNC CONFIDENCE:  ${(dna.bpmConfidence * 100).toFixed(0)}%

[2] SYSTEM IMPACT ANALYSIS
------------------------------------------------------------
This file has been ingested into the global learning weights.
Future generations for the genre "${dna.detectedGenre || 'PSYTRANCE'}" 
will now be influenced by this file's rhythmic DNA.

- INFLUENCE ON MAESTRO ENGINE: High (Rhythm Mask updated)
- INFLUENCE ON LOOP GEN: Active (Motif patterns expanded)
- INFLUENCE ON BRAIN: Persistent (Stored in LocalStorage)

[3] LEGAL & PRIVACY NOTICE
------------------------------------------------------------
This data is processed locally in your browser. 
Only statistical values (Rhythm Masks/Density) are stored.
Original note sequences are discarded after DNA extraction.

============================================================
    GENERATED BY MIDI AI NEURAL TRAINER V1.2
============================================================
    `;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `NEURAL_LEARNING_REPORT_${fileName.split('.')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
};

export const NeuralTrainer: React.FC<NeuralTrainerProps> = ({ onClose }) => {
    const [queue, setQueue] = useState<QueuedFile[]>([]);
    const [isProcessing, setIsProcessing] = useState(false);

    const onDrop = useCallback((acceptedFiles: File[]) => {
        const newFiles = acceptedFiles.map(f => ({
            file: f,
            status: 'PENDING' as const,
            detectedRole: detectRole(f.name)
        }));
        setQueue(prev => [...prev, ...newFiles]);
    }, []);

    const { getRootProps, getInputProps, isDragActive } = useDropzone({
        onDrop,
        accept: { 'audio/midi': ['.mid', '.midi'] }
    });

    const processQueue = async () => {
        setIsProcessing(true);
        const newQueue = [...queue];
        for (let i = 0; i < newQueue.length; i++) {
            if (newQueue[i].status === 'PENDING') {
                newQueue[i].status = 'ANALYZING';
                setQueue([...newQueue]);
                try {
                    const dna = await referenceAnalysisService.analyzeMidi(newQueue[i].file);
                    const genreTag = dna.detectedGenre || 'PSYTRANCE_FULLON';
                    
                    // Ingest into Brain
                    await learningBrainService.ingestMidiKnowledge({
                        fileBuffer: await newQueue[i].file.arrayBuffer(),
                        fileName: newQueue[i].file.name,
                        genre: genreTag,
                        extractedDNA: dna,
                        learningScore: 100,
                        contributionTags: [newQueue[i].detectedRole]
                    });

                    // Persist for aggregates
                    referenceStorageService.saveReference({
                        id: `TRAIN-${Date.now()}-${i}`,
                        name: newQueue[i].file.name,
                        genreTag: genreTag,
                        analysisStatus: 'ANALYZED',
                        analysisResult: dna
                    });

                    // DOWNLOAD THE REPORT
                    downloadLearningReport(newQueue[i].file.name, dna, newQueue[i].detectedRole || 'UNKNOWN');

                    newQueue[i].status = 'LEARNED';
                    newQueue[i].stats = { bpm: dna.bpmEstimate, density: dna.noteDensityAvg };
                } catch (e) {
                    newQueue[i].status = 'FAILED';
                }
                setQueue([...newQueue]);
            }
        }
        setIsProcessing(false);
    };

    return (
        <div className="h-full flex flex-col bg-[#050507] text-white animate-in fade-in" dir="ltr">
            <header className="h-16 md:h-20 bg-[#0A0A0B] border-b border-white/10 flex items-center justify-between px-4 md:px-8 shrink-0">
                <div className="flex items-center gap-3">
                    <button onClick={onClose} className="p-1.5 md:p-2 hover:bg-white/10 rounded-full transition-all text-gray-400">
                        <ArrowLeft size={18} />
                    </button>
                    <div>
                        <h1 className="text-base md:text-2xl font-black uppercase tracking-tighter">
                            Neural <span className="text-purple-500">Trainer</span>
                        </h1>
                        <p className="text-[8px] md:text-[10px] text-gray-500 font-mono uppercase">System-Wide Learning Active</p>
                    </div>
                </div>
                <div className="flex items-center gap-3">
                    <button 
                        onClick={processQueue} 
                        disabled={isProcessing || queue.filter(q => q.status === 'PENDING').length === 0}
                        className="px-4 md:px-8 py-2 md:py-3 bg-purple-600 hover:bg-purple-500 text-white font-bold uppercase text-[10px] md:text-xs tracking-widest rounded-lg md:rounded-xl disabled:opacity-50 transition-all flex items-center gap-2 shadow-lg"
                    >
                        {isProcessing ? <Loader2 size={12} className="animate-spin" /> : <BrainCircuit size={12} />}
                        <span className="hidden sm:inline">{isProcessing ? 'Deconstructing...' : 'Start Training'}</span>
                        <span className="sm:hidden">{isProcessing ? '...' : 'Go'}</span>
                    </button>
                </div>
            </header>

            <div className="flex-1 flex flex-col md:flex-row overflow-hidden">
                <div className="w-full md:w-1/3 bg-[#0E0E10] border-b md:border-b-0 md:border-r border-white/5 p-4 md:p-8 flex flex-col shrink-0">
                    <div 
                        {...getRootProps()} 
                        className={`
                            h-40 md:flex-1 border-2 border-dashed rounded-2xl md:rounded-3xl flex flex-col items-center justify-center cursor-pointer transition-all relative overflow-hidden
                            ${isDragActive ? 'border-purple-500 bg-purple-500/10' : 'border-white/10 hover:border-white/20 hover:bg-white/5'}
                        `}
                    >
                        <input {...getInputProps()} />
                        <Upload className="text-gray-600 mb-2 md:mb-4 w-8 h-8 md:w-12 md:h-12" />
                        <h3 className="text-xs md:text-lg font-bold text-gray-300 uppercase tracking-widest">Drop Reference MIDI</h3>
                        <p className="text-[9px] text-gray-500 mt-2">DNA will be extracted for AI optimization</p>
                    </div>
                    
                    <div className="mt-4 md:mt-6 p-4 md:p-6 bg-purple-900/10 border border-purple-500/20 rounded-xl md:rounded-2xl space-y-4">
                        <div className="flex items-center gap-3">
                            <ShieldCheck className="text-green-500" size={20} />
                            <h4 className="text-[10px] md:text-xs font-black text-white uppercase tracking-widest">Learning Protocol</h4>
                        </div>
                        <p className="text-[9px] md:text-[10px] text-gray-400 leading-relaxed font-medium">
                            כל קובץ שנטען עובר ניתוח "Forensic" ומשפיע על משקלי הייצור בכל הכלים במערכת (Maestro, Loop Gen). הדו"ח שתקבל יפרט את השינויים שבוצעו ב"מוח" המערכת.
                        </p>
                    </div>
                </div>

                <div className="flex-1 overflow-y-auto p-4 md:p-8 custom-scrollbar bg-[#050507]">
                    <div className="flex justify-between items-center mb-6">
                        <h3 className="text-[10px] md:text-xs font-black text-gray-500 uppercase tracking-widest">Training Queue ({queue.length})</h3>
                        <div className="flex items-center gap-2">
                             <div className="w-2 h-2 bg-purple-500 rounded-full animate-pulse"></div>
                             <span className="text-[9px] text-gray-400 font-bold uppercase">Learning Engine: Online</span>
                        </div>
                    </div>
                    
                    <div className="space-y-3">
                        {queue.length === 0 ? (
                            <div className="flex flex-col items-center justify-center py-20 opacity-20 text-center space-y-4">
                                <div className="w-16 h-16 rounded-full border border-white/20 flex items-center justify-center">
                                    <FileCode size={32} />
                                </div>
                                <p className="text-xs font-black uppercase tracking-widest">No active training files</p>
                            </div>
                        ) : (
                            queue.map((item, idx) => (
                                <div key={idx} className={`bg-[#111] border rounded-xl p-4 flex flex-col md:flex-row md:items-center justify-between gap-4 transition-all ${
                                    item.status === 'LEARNED' ? 'border-green-500/30 bg-green-900/5' : 'border-white/5'
                                }`}>
                                    <div className="flex items-center gap-4 min-w-0">
                                        <div className={`w-10 h-10 rounded-lg flex items-center justify-center font-black text-xs shrink-0 border ${
                                            item.status === 'LEARNED' ? 'bg-green-500 border-green-500 text-black' : 'bg-gray-800 border-white/10 text-gray-500'
                                        }`}>
                                            {item.status === 'LEARNED' ? '✓' : idx + 1}
                                        </div>
                                        <div className="min-w-0">
                                            <div className="font-black text-sm text-white truncate">{item.file.name}</div>
                                            <div className="flex gap-2 items-center mt-1">
                                                <span className="text-[9px] bg-white/5 px-2 py-0.5 rounded text-gray-400 font-bold uppercase">{item.detectedRole.replace('ch', 'Channel ')}</span>
                                                {item.status === 'LEARNED' && <span className="text-[8px] text-green-500 font-black uppercase flex items-center gap-1"><FileText size={10} /> Report Generated</span>}
                                            </div>
                                        </div>
                                    </div>
                                    <div className="flex items-center gap-4 shrink-0">
                                        {item.status === 'ANALYZING' && (
                                            <div className="flex items-center gap-2 text-blue-400 font-bold text-[10px] uppercase">
                                                <Loader2 size={14} className="animate-spin" /> Analyzing Patterns
                                            </div>
                                        )}
                                        {item.status === 'LEARNED' && (
                                            <div className="flex items-center gap-3">
                                                <div className="text-right hidden sm:block">
                                                    <div className="text-[10px] font-black text-white">{item.stats.bpm} BPM</div>
                                                    <div className="text-[8px] text-gray-500 font-mono">DENSITY: {item.stats.density.toFixed(2)}</div>
                                                </div>
                                                <CheckCircle size={20} className="text-green-500" />
                                            </div>
                                        )}
                                        {item.status === 'FAILED' && <AlertTriangle size={20} className="text-red-500" />}
                                    </div>
                                </div>
                            ))
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
};
